services:
  mystore.api:
    image: ${DOCKER_REGISTRY-}mystoreapi
    build:
      context: .
      dockerfile: MyStore.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=my_app_db;Username=admin;Password=password123
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
      warehouse: 
        condition: service_started

  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:latest
    container_name: my_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "8090:80"
      - "5341:5341"
    volumes:
      - seq_data:/data

  warehouse:
    image: ${DOCKER_REGISTRY-}mystorewarehouse
    build:
      context: .
      dockerfile: MyStore.Warehouse/Dockerfile
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KESTREL__ENDPOINTS__GRPC__URL=http://0.0.0.0:8080
      - KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
      - ConnectionStrings__WarehouseDb=Host=db;Port=5432;Database=my_app_db;Username=admin;Password=password123
      - MessageBroker__Host=rabbitmq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: my_jaeger
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"   

  grafana:
    image: grafana/grafana:latest
    container_name: my_grafana
    restart: always
    ports:
      - "3000:3000" # (admin/admin)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data:
  seq_data:
